baseurl = "https://vult-dsp.github.io/vult/"
languageCode = "en-us"
title = "Vult Language"
theme = "vult"

relativeURLs = "true"

disqusShortname = "vult-dsp"
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

