(ocamllex baseTok)

(library
 (name util)
 (public_name vult.util)
 (modules
  Binarize
  Components
  Error
  FileIO
  Vfloat
  Loc
  Args
  Maps
  Fitting
  WaveFile
  Profile
  Diff
  BaseTok)
 (libraries containers pla str)
 (preprocess
  (pps pla.ppx))
 (ocamlopt_flags -O3 -unbox-closures)
 (instrumentation
  (backend bisect_ppx)))
