let legend =
  let version = Core.Version.version in
  {pla|/* This code was generated by the Vult compiler <#version#s> https://github.com/modlfo/vult */|pla}


let setExt ext output =
  match output with
  | None -> "output" ^ ext
  | Some file -> file ^ ext
