(library
 (name generators)
 (modules
  Lua
  Js
  Cpp
  Java
  Julia
  Python
  Common
  Tocode
  Tables
  T_pd
  T_performance
  T_mathematica
  T_browser
  T_webaudio
  T_worklet
  Replacements)
 (libraries core pparser pla str util)
 (flags
  (:standard -w -30))
 (preprocess
  (pps pla.ppx))
 (ocamlopt_flags -O3 -unbox-closures)
 (instrumentation
  (backend bisect_ppx)))
