/* This code was generated by the Vult compiler v1-dev https://github.com/vult-dsp/vult */
#ifndef TEST_SERIALIZATION_H
#define TEST_SERIALIZATION_H

#include "vultin.hpp"
#include "test_serialization.tables.h"

typedef struct Test_serialization_point {
   float x;
   float y;
} Test_serialization_point;

typedef struct Test_serialization_rect {
   Test_serialization_point origin;
   Test_serialization_point size;
} Test_serialization_rect;

typedef struct Test_serialization_main_type {
   bool bool_val;
   std::array<int32_t, 4> int_arr;
   mutable std::vector<int32_t> int_list;
   int32_t int_val;
   Test_serialization_point pt;
   std::array<Test_serialization_point, 3> pt_arr;
   mutable std::vector<Test_serialization_point> pt_list;
   Test_serialization_rect rc;
   float real_val;
   std::string str_1;
   std::string str_15;
   std::string str_16;
   std::string str_2;
   std::string str_3;
   std::string str_31;
   std::string str_32;
   std::string str_4;
   std::string str_5;
   std::string str_7;
   std::string str_8;
   std::string str_empty;
   std::string str_val;
} Test_serialization_main_type;

typedef struct Test_serialization_main_type Test_serialization_setTestValues_type;

static_inline void Test_serialization_point_init(Test_serialization_point& _ctx) {
   _ctx.x = 0.0f;
   _ctx.y = 0.0f;
}

static_inline void Test_serialization_rect_init(Test_serialization_rect& _ctx) {
   Test_serialization_point_init(_ctx.origin);
   Test_serialization_point_init(_ctx.size);
}

void Test_serialization_setTestValues(Test_serialization_main_type& _ctx);

void Test_serialization_main_type_init(Test_serialization_main_type& _ctx);

static_inline void Test_serialization_setTestValues_type_init(Test_serialization_setTestValues_type& _ctx) {
   Test_serialization_main_type_init(_ctx);
}

int32_t Test_serialization_point_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_point& _ctx);

int32_t Test_serialization_rect_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_rect& _ctx);

int32_t Test_serialization_main_type_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_main_type& _ctx);

static_inline int32_t Test_serialization_setTestValues_type_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_setTestValues_type& _ctx) {
   return Test_serialization_main_type_serialize_data(buffer, index, _ctx);
}

static_inline int32_t Test_serialization_point_serialize_type_descr(CustomBuffer& buffer, int32_t index, std::array<bool, 4>& marks) {
   if (marks[static_cast<uint32_t>(1)]) {
      return index;
   }
   marks[static_cast<uint32_t>(1)] = true;
   std::array<std::string, 2> _array_0 = { "x", "y" };
   return serialize_type_descr(buffer, index, "Test_serialization_point", _array_0);
}

static_inline int32_t Test_serialization_rect_serialize_type_descr(CustomBuffer& buffer, int32_t index, std::array<bool, 4>& marks) {
   if (marks[static_cast<uint32_t>(2)]) {
      return index;
   }
   marks[static_cast<uint32_t>(2)] = true;
   index = Test_serialization_point_serialize_type_descr(buffer, index, marks);
   std::array<std::string, 2> _array_0 = { "origin", "size" };
   return serialize_type_descr(buffer, index, "Test_serialization_rect", _array_0);
}

int32_t Test_serialization_main_type_serialize_type_descr(CustomBuffer& buffer, int32_t index, std::array<bool, 4>& marks);

void Test_serialization_point_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_point& _ctx);

void Test_serialization_rect_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_rect& _ctx);

void Test_serialization_main_type_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_main_type& _ctx);

static_inline void Test_serialization_main(Test_serialization_main_type& _ctx) {
}


#endif // TEST_SERIALIZATION_H
