/* This code was generated by the Vult compiler v1-dev https://github.com/vult-dsp/vult */

#include "test_serialization.h"

void Test_serialization_setTestValues(Test_serialization_main_type& _ctx) {
   _ctx.int_val = 42;
   _ctx.real_val = 3.14159f;
   _ctx.bool_val = true;
   _ctx.str_val = "Hello, World!";
   _ctx.str_empty = "";
   _ctx.str_1 = "A";
   _ctx.str_2 = "AB";
   _ctx.str_3 = "ABC";
   _ctx.str_4 = "ABCD";
   _ctx.str_5 = "ABCDE";
   _ctx.str_7 = "ABCDEFG";
   _ctx.str_8 = "ABCDEFGH";
   _ctx.str_15 = "ABCDEFGHIJKLMNO";
   _ctx.str_16 = "ABCDEFGHIJKLMNOP";
   _ctx.str_31 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ01234";
   _ctx.str_32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345";
   _ctx.pt.x = 10.0f;
   _ctx.pt.y = 20.0f;
   _ctx.rc.origin.x = 0.0f;
   _ctx.rc.origin.y = 0.0f;
   _ctx.rc.size.x = 100.0f;
   _ctx.rc.size.y = 50.0f;
   _ctx.int_arr[static_cast<uint32_t>(0)] = 1;
   _ctx.int_arr[static_cast<uint32_t>(1)] = 2;
   _ctx.int_arr[static_cast<uint32_t>(2)] = 3;
   _ctx.int_arr[static_cast<uint32_t>(3)] = 4;
   _ctx.pt_arr[static_cast<uint32_t>(0)].x = 1.0f;
   _ctx.pt_arr[static_cast<uint32_t>(0)].y = 1.0f;
   _ctx.pt_arr[static_cast<uint32_t>(1)].x = 2.0f;
   _ctx.pt_arr[static_cast<uint32_t>(1)].y = 2.0f;
   _ctx.pt_arr[static_cast<uint32_t>(2)].x = 3.0f;
   _ctx.pt_arr[static_cast<uint32_t>(2)].y = 3.0f;
   _ctx.int_list.push_back(100);
   _ctx.int_list.push_back(200);
   _ctx.int_list.push_back(300);
   const Test_serialization_point _record_0 = { 5.0f, 6.0f };
   _ctx.pt_list.push_back(_record_0);
   const Test_serialization_point _record_1 = { 7.0f, 8.0f };
   _ctx.pt_list.push_back(_record_1);
}

void Test_serialization_main_type_init(Test_serialization_main_type& _ctx) {
   _ctx.bool_val = false;
   int32_t i_0 = 0;
   while (i_0 < 4) {
      _ctx.int_arr[static_cast<uint32_t>(i_0)] = 0;
      i_0 = 1 + i_0;
   }
   _ctx.int_list = {};
   _ctx.int_val = 0;
   Test_serialization_point_init(_ctx.pt);
   int32_t i_1 = 0;
   while (i_1 < 3) {
      Test_serialization_point_init(_ctx.pt_arr[static_cast<uint32_t>(i_1)]);
      i_1 = 1 + i_1;
   }
   _ctx.pt_list = {};
   Test_serialization_rect_init(_ctx.rc);
   _ctx.real_val = 0.0f;
   _ctx.str_1 = "";
   _ctx.str_15 = "";
   _ctx.str_16 = "";
   _ctx.str_2 = "";
   _ctx.str_3 = "";
   _ctx.str_31 = "";
   _ctx.str_32 = "";
   _ctx.str_4 = "";
   _ctx.str_5 = "";
   _ctx.str_7 = "";
   _ctx.str_8 = "";
   _ctx.str_empty = "";
   _ctx.str_val = "";
   Test_serialization_setTestValues(_ctx);
}

int32_t Test_serialization_point_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_point& _ctx) {
   int32_t start = index;
   index = push_block_header(buffer, index);
   index = push_float(buffer, index, _ctx.x);
   index = push_float(buffer, index, _ctx.y);
   update_size(buffer, start, index + (- start));
   return index;
}

int32_t Test_serialization_rect_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_rect& _ctx) {
   int32_t start = index;
   index = push_block_header(buffer, index);
   index = Test_serialization_point_serialize_data(buffer, index, _ctx.origin);
   index = Test_serialization_point_serialize_data(buffer, index, _ctx.size);
   update_size(buffer, start, index + (- start));
   return index;
}

int32_t Test_serialization_main_type_serialize_data(CustomBuffer& buffer, int32_t index, const Test_serialization_main_type& _ctx) {
   int32_t start = index;
   index = push_block_header(buffer, index);
   index = push_int(buffer, index, _ctx.bool_val);
   int32_t start_0 = index;
   index = push_array(buffer, index, 4);
   int32_t i_0 = 0;
   while (i_0 < 4) {
      index = push_int(buffer, index, _ctx.int_arr[static_cast<uint32_t>(i_0)]);
      i_0 = 1 + i_0;
   }
   update_size(buffer, start_0, index + (- start_0));
   int32_t size_1 = static_cast<int32_t>(_ctx.int_list.size());
   int32_t start_1 = index;
   index = push_array(buffer, index, size_1);
   int32_t i_1 = 0;
   while (i_1 < size_1) {
      index = push_int(buffer, index, _ctx.int_list[static_cast<uint32_t>(i_1)]);
      i_1 = 1 + i_1;
   }
   update_size(buffer, start_1, index + (- start_1));
   index = push_int(buffer, index, _ctx.int_val);
   index = Test_serialization_point_serialize_data(buffer, index, _ctx.pt);
   int32_t start_2 = index;
   index = push_array(buffer, index, 3);
   int32_t i_2 = 0;
   while (i_2 < 3) {
      index = Test_serialization_point_serialize_data(buffer, index, _ctx.pt_arr[static_cast<uint32_t>(i_2)]);
      i_2 = 1 + i_2;
   }
   update_size(buffer, start_2, index + (- start_2));
   int32_t size_3 = static_cast<int32_t>(_ctx.pt_list.size());
   int32_t start_3 = index;
   index = push_array(buffer, index, size_3);
   int32_t i_3 = 0;
   while (i_3 < size_3) {
      index = Test_serialization_point_serialize_data(buffer, index, _ctx.pt_list[static_cast<uint32_t>(i_3)]);
      i_3 = 1 + i_3;
   }
   update_size(buffer, start_3, index + (- start_3));
   index = Test_serialization_rect_serialize_data(buffer, index, _ctx.rc);
   index = push_float(buffer, index, _ctx.real_val);
   index = push_string(buffer, index, _ctx.str_1);
   index = push_string(buffer, index, _ctx.str_15);
   index = push_string(buffer, index, _ctx.str_16);
   index = push_string(buffer, index, _ctx.str_2);
   index = push_string(buffer, index, _ctx.str_3);
   index = push_string(buffer, index, _ctx.str_31);
   index = push_string(buffer, index, _ctx.str_32);
   index = push_string(buffer, index, _ctx.str_4);
   index = push_string(buffer, index, _ctx.str_5);
   index = push_string(buffer, index, _ctx.str_7);
   index = push_string(buffer, index, _ctx.str_8);
   index = push_string(buffer, index, _ctx.str_empty);
   index = push_string(buffer, index, _ctx.str_val);
   update_size(buffer, start, index + (- start));
   return index;
}

int32_t Test_serialization_main_type_serialize_type_descr(CustomBuffer& buffer, int32_t index, std::array<bool, 4>& marks) {
   if (marks[static_cast<uint32_t>(0)]) {
      return index;
   }
   marks[static_cast<uint32_t>(0)] = true;
   index = Test_serialization_point_serialize_type_descr(buffer, index, marks);
   index = Test_serialization_rect_serialize_type_descr(buffer, index, marks);
   std::array<std::string, 22> _array_0 = { "bool_val", "int_arr", "int_list", "int_val", "pt", "pt_arr", "pt_list", "rc", "real_val", "str_1", "str_15", "str_16", "str_2", "str_3", "str_31", "str_32", "str_4", "str_5", "str_7", "str_8", "str_empty", "str_val" };
   return serialize_type_descr(buffer, index, "Test_serialization_main_type", _array_0);
}

void Test_serialization_point_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_point& _ctx) {
   int32_t field_index = search_field_name(buffer, type_descr, index, "x");
   if (field_index >= 0) {
      _ctx.x = deserialize_float(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "y");
   if (field_index >= 0) {
      _ctx.y = deserialize_float(buffer, field_index);
   }
}

void Test_serialization_rect_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_rect& _ctx) {
   int32_t field_index = search_field_name(buffer, type_descr, index, "origin");
   if (field_index >= 0) {
      CustomTypeDescr field_descr_0 = search_type_description(buffer, "Test_serialization_point");
      Test_serialization_point_deserialize_data(buffer, field_descr_0, field_index, _ctx.origin);
   }
   field_index = search_field_name(buffer, type_descr, index, "size");
   if (field_index >= 0) {
      CustomTypeDescr field_descr_1 = search_type_description(buffer, "Test_serialization_point");
      Test_serialization_point_deserialize_data(buffer, field_descr_1, field_index, _ctx.size);
   }
}

void Test_serialization_main_type_deserialize_data(CustomBuffer& buffer, CustomTypeDescr& type_descr, int32_t index, Test_serialization_main_type& _ctx) {
   int32_t field_index = search_field_name(buffer, type_descr, index, "bool_val");
   if (field_index >= 0) {
      _ctx.bool_val = deserialize_int(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "int_arr");
   if (field_index >= 0) {
      field_index = first_array_element(buffer, field_index);
      int32_t i_1 = 0;
      while (i_1 < 4) {
         _ctx.int_arr[static_cast<uint32_t>(i_1)] = deserialize_int(buffer, field_index);
         i_1 = 1 + i_1;
         field_index = next_object(buffer, field_index);
      }
   }
   field_index = search_field_name(buffer, type_descr, index, "int_list");
   if (field_index >= 0) {
      int32_t list_size_4 = get_array_count(buffer, field_index);
      _ctx.int_list.clear();
      field_index = first_array_element(buffer, field_index);
      int32_t i_3 = 0;
      int32_t temp_5 = 0;
      while (i_3 < list_size_4) {
         temp_5 = deserialize_int(buffer, field_index);
         _ctx.int_list.push_back(temp_5);
         i_3 = 1 + i_3;
         field_index = next_object(buffer, field_index);
      }
   }
   field_index = search_field_name(buffer, type_descr, index, "int_val");
   if (field_index >= 0) {
      _ctx.int_val = deserialize_int(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "pt");
   if (field_index >= 0) {
      CustomTypeDescr field_descr_5 = search_type_description(buffer, "Test_serialization_point");
      Test_serialization_point_deserialize_data(buffer, field_descr_5, field_index, _ctx.pt);
   }
   CustomTypeDescr field_descr_6 = search_type_description(buffer, "Test_serialization_point");
   field_index = search_field_name(buffer, type_descr, index, "pt_arr");
   if (field_index >= 0) {
      field_index = first_array_element(buffer, field_index);
      int32_t i_7 = 0;
      while (i_7 < 3) {
         Test_serialization_point_deserialize_data(buffer, field_descr_6, field_index, _ctx.pt_arr[static_cast<uint32_t>(i_7)]);
         i_7 = 1 + i_7;
         field_index = next_object(buffer, field_index);
      }
   }
   CustomTypeDescr field_descr_8 = search_type_description(buffer, "Test_serialization_point");
   field_index = search_field_name(buffer, type_descr, index, "pt_list");
   if (field_index >= 0) {
      int32_t list_size_10 = get_array_count(buffer, field_index);
      _ctx.pt_list.clear();
      field_index = first_array_element(buffer, field_index);
      int32_t i_9 = 0;
      Test_serialization_point temp_11;
      Test_serialization_point_init(temp_11);
      while (i_9 < list_size_10) {
         Test_serialization_point_deserialize_data(buffer, field_descr_8, field_index, temp_11);
         _ctx.pt_list.push_back(temp_11);
         i_9 = 1 + i_9;
         field_index = next_object(buffer, field_index);
      }
   }
   field_index = search_field_name(buffer, type_descr, index, "rc");
   if (field_index >= 0) {
      CustomTypeDescr field_descr_11 = search_type_description(buffer, "Test_serialization_rect");
      Test_serialization_rect_deserialize_data(buffer, field_descr_11, field_index, _ctx.rc);
   }
   field_index = search_field_name(buffer, type_descr, index, "real_val");
   if (field_index >= 0) {
      _ctx.real_val = deserialize_float(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_1");
   if (field_index >= 0) {
      _ctx.str_1 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_15");
   if (field_index >= 0) {
      _ctx.str_15 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_16");
   if (field_index >= 0) {
      _ctx.str_16 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_2");
   if (field_index >= 0) {
      _ctx.str_2 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_3");
   if (field_index >= 0) {
      _ctx.str_3 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_31");
   if (field_index >= 0) {
      _ctx.str_31 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_32");
   if (field_index >= 0) {
      _ctx.str_32 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_4");
   if (field_index >= 0) {
      _ctx.str_4 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_5");
   if (field_index >= 0) {
      _ctx.str_5 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_7");
   if (field_index >= 0) {
      _ctx.str_7 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_8");
   if (field_index >= 0) {
      _ctx.str_8 = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_empty");
   if (field_index >= 0) {
      _ctx.str_empty = deserialize_string(buffer, field_index);
   }
   field_index = search_field_name(buffer, type_descr, index, "str_val");
   if (field_index >= 0) {
      _ctx.str_val = deserialize_string(buffer, field_index);
   }
}

