/* This code was generated by the Vult compiler v1-dev https://github.com/vult-dsp/vult */
#ifndef TEST_SERIALIZATION_TABLES_H
#define TEST_SERIALIZATION_TABLES_H

#endif // TEST_SERIALIZATION_TABLES_H
