<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vult</string>
	</array>
	<key>name</key>
	<string>Vult</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.Vult</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.Vult</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(fun|and|external)\s+([a-zA-Z_]\w*)</string>
			<key>name</key>
			<string>meta.function.source.Vult</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fun|val|mem|return|if|else|while|then|type|table|external)\b</string>
			<key>name</key>
			<string>keyword.source.Vult</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.source.Vult</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|real|num|bool)\b</string>
			<key>name</key>
			<string>storage.type.source.Vult</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.Vult</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.source.Vult</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_]\w*)\b(\()</string>
			<key>name</key>
			<string>storage.type.source.Vult</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.source.Vult</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.Vult</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.Vult</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.Vult</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.Vult</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.begin.source.Vult</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.end.source.Vult</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.source.Vult</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.Vult</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|:|;|&lt;|&gt;|,|!=|\+|\*|/|-|\||&amp;|\(|\)|{|})</string>
			<key>name</key>
			<string>constant.character.source.Vult</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false)</string>
			<key>name</key>
			<string>constant.language.source.Vult</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.Vult</string>
	<key>uuid</key>
	<string>42b15ba4-ffb5-4aad-9446-3885a88d8938</string>
</dict>
</plist>
