(library
 (name core)
 (public_name vult.core)
 (modules
  Typed
  Prog
  Toprog
  Typechecking
  Elaboration
  Env
  Mapper
  Passes
  Version
  Initializer
  Serializer
  Interpreter)
 (libraries util pparser pla)
 (flags
  (:standard -w -30))
 (preprocess
  (pps pla.ppx))
 (ocamlopt_flags -O3 -unbox-closures)
 (instrumentation
  (backend bisect_ppx)))
