(*
The MIT License (MIT)

Copyright (c) 2014 Leonardo Laguna Ruiz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*)

(** Template for the Teensy Audio library *)


(** Header function *)
let header (_:string) (output:string) (code:Pla.t) : Pla.t =
   let file = String.uppercase output in
   {pla|
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef <#file#s>_H
#define <#file#s>_H

#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include <m_pd.h>

<#code#>

#endif // <#file#s>_H
|pla}


(** Implementation function *)
let implementation (module_name:string) (output:string) (code:Pla.t) : Pla.t =
   {pla|
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "<#output#s>.h"

<#code#>

extern "C" {

static t_class *<#output#s>_tilde_class;

typedef struct _<#output#s>_tilde {
  t_object  x_obj;
  float dummy;
  <#module_name#s>_process_type data;
} t_<#output#s>_tilde;

t_int *<#output#s>_tilde_perform(t_int *w)
{
  t_<#output#s>_tilde *x = (t_<#output#s>_tilde *)(w[1]);
  t_sample      *in = (t_sample *)(w[2]);
  t_sample     *out = (t_sample *)(w[3]);
  int             n = (int)(w[4]);

  while (n--) *out++ = <#module_name#s>_process(x->data,*(in++));

  return (w+5);
}

void <#output#s>_tilde_dsp(t_<#output#s>_tilde *x, t_signal **sp)
{
  dsp_add(<#output#s>_tilde_perform, 4,
          x,
          sp[0]->s_vec,
          sp[1]->s_vec,
          sp[0]->s_n);
}

void *<#output#s>_tilde_new()
{
  t_<#output#s>_tilde *x = (t_<#output#s>_tilde *)pd_new(<#output#s>_tilde_class);

  x->data = <#module_name#s>_process_init();
  <#module_name#s>_default(x->data);
  outlet_new(&x->x_obj, &s_signal);

  return (void *)x;
}

void <#output#s>_tilde_delete(t_<#output#s>_tilde *x){

}

void <#output#s>_noteOn(t_<#output#s>_tilde *x, t_floatarg note, t_floatarg velocity){
  if((int)velocity) <#module_name#s>_noteOn(x->data, (int)note, (int)velocity);
  else <#module_name#s>_noteOff(x->data, (int)note);
}

void <#output#s>_noteOff(t_<#output#s>_tilde *x, t_floatarg note) {
  <#module_name#s>_noteOff(x->data, (int)note);
}

void <#output#s>_controlChange(t_<#output#s>_tilde *x, t_floatarg control, t_floatarg value) {
  <#module_name#s>_controlChange(x->data, (int)control, (int)value);
}

void <#output#s>_tilde_setup(void) {
  <#output#s>_tilde_class = class_new(gensym("<#output#s>~"),
        (t_newmethod)<#output#s>_tilde_new, // constructor function
        (t_method)<#output#s>_tilde_delete, // destructor function
        sizeof(t_<#output#s>_tilde), // size of the object
        CLASS_DEFAULT, // type of object
        A_NULL); // arguments passed

  class_addmethod(<#output#s>_tilde_class,
        (t_method)<#output#s>_tilde_dsp, gensym("dsp"), A_NULL);
  CLASS_MAINSIGNALIN(<#output#s>_tilde_class, t_<#output#s>_tilde, dummy);

  class_addmethod(<#output#s>_tilde_class, (t_method)<#output#s>_noteOn,        gensym("noteOn"),        A_DEFFLOAT, A_DEFFLOAT, A_NULL);
  class_addmethod(<#output#s>_tilde_class, (t_method)<#output#s>_noteOff,       gensym("noteOff"),       A_DEFFLOAT, A_NULL);
  class_addmethod(<#output#s>_tilde_class, (t_method)<#output#s>_controlChange, gensym("controlChange"), A_DEFFLOAT, A_DEFFLOAT, A_NULL);

}

} // extern "C"
|pla}

let get = header, implementation
