name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    permissions:
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only

      - run: opam exec -- make

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: _build/default/src/vult.exe
          
      - name: Save Js VultcJs Artifacts
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: vult.js
          path: vult.js

      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.ocaml-compiler }}-vult.exe
          path: _build/default/src/vult.exe
